packages:
  # Core packages
  - 'packages/*'            # All packages in the packages directory
  
  # Applications
  - 'apps/*'               # All applications
  - 'apps/web'             # Next.js application
  - 'apps/docs'            # Documentation site (if needed)
  
  # Development tools and examples
  - 'examples/*'           # Example implementations
  - 'tools/*'              # Development tooling
  
  # Exclude directories
  - '!**/dist'             # Exclude all dist directories
  - '!**/build'            # Exclude all build directories
  - '!**/node_modules'     # Exclude all node_modules directories
  - '!**/test'             # Exclude test directories from workspace

# To prevent hoisting, ensure no shared node_modules at the root
hoist-pattern: []

# This will ensure isolated node_modules for each package
store: ~/.pnpm-store
